//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProductionItem
    {
        public string SerialNo { get; set; }
        public string VarItemID { get; set; }
        public string VarItemName { get; set; }
        public Nullable<int> FactoryUnitId { get; set; }
        public string FactoryUnitName { get; set; }
        public Nullable<double> McA { get; set; }
        public Nullable<double> AKg { get; set; }
        public Nullable<double> McB { get; set; }
        public Nullable<double> BKg { get; set; }
        public double PackingProductionKG { get; set; }
        public double PackingProductionMT { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
