//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyFinalize
    {
        public System.DateTime DDate { get; set; }
        public long Unit { get; set; }
        public Nullable<double> TotalSP { get; set; }
        public Nullable<double> TotalTW { get; set; }
        public Nullable<double> TotalPR { get; set; }
        public Nullable<double> TotalPK { get; set; }
        public Nullable<double> TotalLM { get; set; }
        public Nullable<double> TotalHandPerTon { get; set; }
        public Nullable<double> TotalBagPerPerson { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    }
}
