//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishGoodItem
    {
        public string VarItemCode { get; set; }
        public string VarItemName { get; set; }
        public string NameShort { get; set; }
        public string Quality { get; set; }
        public double VarCount { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> ThicknessMulti { get; set; }
        public string ItemType { get; set; }
        public string Active { get; set; }
    }
}
