//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoomFinalize
    {
        public long Id { get; set; }
        public Nullable<long> Unit { get; set; }
        public string Yearn { get; set; }
        public string Item { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> QtyPcs { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
    }
}
