//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductionsFinalizeEntities1 : DbContext
    {
        public ProductionsFinalizeEntities1()
            : base("name=ProductionsFinalizeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailyFinalize> DailyFinalizes { get; set; }
        public virtual DbSet<DailyPrecisionWindingProduction> DailyPrecisionWindingProductions { get; set; }
        public virtual DbSet<DailyPrecisionWindingProduction2> DailyPrecisionWindingProduction2 { get; set; }
        public virtual DbSet<DailySpinningWindingProduction> DailySpinningWindingProductions { get; set; }
        public virtual DbSet<DailyTwistingProduction> DailyTwistingProductions { get; set; }
        public virtual DbSet<FactoryUnit> FactoryUnits { get; set; }
        public virtual DbSet<LoomFinalize> LoomFinalizes { get; set; }
        public virtual DbSet<LoomProduction> LoomProductions { get; set; }
        public virtual DbSet<PackingFinalize> PackingFinalizes { get; set; }
        public virtual DbSet<PowerHistoryFinalize> PowerHistoryFinalizes { get; set; }
        public virtual DbSet<PowerHistoryLoomFinalize> PowerHistoryLoomFinalizes { get; set; }
        public virtual DbSet<SpinningTwistingPrecisionProductionFinalize> SpinningTwistingPrecisionProductionFinalizes { get; set; }
        public virtual DbSet<SummaryLoomFinalize> SummaryLoomFinalizes { get; set; }
        public virtual DbSet<SummarySpinningFinalize> SummarySpinningFinalizes { get; set; }
        public virtual DbSet<DailyFinalize2> DailyFinalize2 { get; set; }
        public virtual DbSet<DailyProductionItem> DailyProductionItems { get; set; }
        public virtual DbSet<DepartmentType> DepartmentTypes { get; set; }
        public virtual DbSet<FinishGoodItem> FinishGoodItems { get; set; }
        public virtual DbSet<LoomFinalize2> LoomFinalize2 { get; set; }
        public virtual DbSet<PackingFinalize2> PackingFinalize2 { get; set; }
        public virtual DbSet<PowerHistoryFinalize2> PowerHistoryFinalize2 { get; set; }
        public virtual DbSet<PowerHistoryLoomFinalize2> PowerHistoryLoomFinalize2 { get; set; }
        public virtual DbSet<PrecisionProductionFinalize2> PrecisionProductionFinalize2 { get; set; }
        public virtual DbSet<SpinningTwistingProductionFinalize2> SpinningTwistingProductionFinalize2 { get; set; }
        public virtual DbSet<SummaryLoomFinalize2> SummaryLoomFinalize2 { get; set; }
        public virtual DbSet<SummarySpinningFinalize2> SummarySpinningFinalize2 { get; set; }
    
        public virtual ObjectResult<string> SaveFinalize(string sTP_ProductionFinalizeString, string packingFinalizeString, string loomFinalizeString, string summarySpinningFinalizeString, string summaryLoomFinalizeString, string powerHistoryFinalizeString, string powerHistoryLoomFinalizeString, string oldInvoice, string pdFirst, string pdSecond, string pFirst, Nullable<System.DateTime> date, Nullable<long> unit, string dailyFinalize)
        {
            var sTP_ProductionFinalizeStringParameter = sTP_ProductionFinalizeString != null ?
                new ObjectParameter("STP_ProductionFinalizeString", sTP_ProductionFinalizeString) :
                new ObjectParameter("STP_ProductionFinalizeString", typeof(string));
    
            var packingFinalizeStringParameter = packingFinalizeString != null ?
                new ObjectParameter("PackingFinalizeString", packingFinalizeString) :
                new ObjectParameter("PackingFinalizeString", typeof(string));
    
            var loomFinalizeStringParameter = loomFinalizeString != null ?
                new ObjectParameter("LoomFinalizeString", loomFinalizeString) :
                new ObjectParameter("LoomFinalizeString", typeof(string));
    
            var summarySpinningFinalizeStringParameter = summarySpinningFinalizeString != null ?
                new ObjectParameter("SummarySpinningFinalizeString", summarySpinningFinalizeString) :
                new ObjectParameter("SummarySpinningFinalizeString", typeof(string));
    
            var summaryLoomFinalizeStringParameter = summaryLoomFinalizeString != null ?
                new ObjectParameter("SummaryLoomFinalizeString", summaryLoomFinalizeString) :
                new ObjectParameter("SummaryLoomFinalizeString", typeof(string));
    
            var powerHistoryFinalizeStringParameter = powerHistoryFinalizeString != null ?
                new ObjectParameter("PowerHistoryFinalizeString", powerHistoryFinalizeString) :
                new ObjectParameter("PowerHistoryFinalizeString", typeof(string));
    
            var powerHistoryLoomFinalizeStringParameter = powerHistoryLoomFinalizeString != null ?
                new ObjectParameter("PowerHistoryLoomFinalizeString", powerHistoryLoomFinalizeString) :
                new ObjectParameter("PowerHistoryLoomFinalizeString", typeof(string));
    
            var oldInvoiceParameter = oldInvoice != null ?
                new ObjectParameter("OldInvoice", oldInvoice) :
                new ObjectParameter("OldInvoice", typeof(string));
    
            var pdFirstParameter = pdFirst != null ?
                new ObjectParameter("pdFirst", pdFirst) :
                new ObjectParameter("pdFirst", typeof(string));
    
            var pdSecondParameter = pdSecond != null ?
                new ObjectParameter("pdSecond", pdSecond) :
                new ObjectParameter("pdSecond", typeof(string));
    
            var pFirstParameter = pFirst != null ?
                new ObjectParameter("pFirst", pFirst) :
                new ObjectParameter("pFirst", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var unitParameter = unit.HasValue ?
                new ObjectParameter("Unit", unit) :
                new ObjectParameter("Unit", typeof(long));
    
            var dailyFinalizeParameter = dailyFinalize != null ?
                new ObjectParameter("DailyFinalize", dailyFinalize) :
                new ObjectParameter("DailyFinalize", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SaveFinalize", sTP_ProductionFinalizeStringParameter, packingFinalizeStringParameter, loomFinalizeStringParameter, summarySpinningFinalizeStringParameter, summaryLoomFinalizeStringParameter, powerHistoryFinalizeStringParameter, powerHistoryLoomFinalizeStringParameter, oldInvoiceParameter, pdFirstParameter, pdSecondParameter, pFirstParameter, dateParameter, unitParameter, dailyFinalizeParameter);
        }
    
        [DbFunction("ProductionsFinalizeEntities1", "split")]
        public virtual IQueryable<split_Result> split(string delimited, string delimiter)
        {
            var delimitedParameter = delimited != null ?
                new ObjectParameter("delimited", delimited) :
                new ObjectParameter("delimited", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<split_Result>("[ProductionsFinalizeEntities1].[split](@delimited, @delimiter)", delimitedParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<string> SaveFinalize2(string sTP_ProductionFinalize2String, string precision_ProductionFinalize2String, string packingFinalize2String, string loomFinalize2String, string summarySpinningFinalize2String, string summaryLoomFinalize2String, string powerHistoryFinalize2String, string powerHistoryLoomFinalize2String, string oldInvoice, string pdFirst, string pdSecond, string pFirst, Nullable<System.DateTime> date, Nullable<long> unit, string dailyFinalize2)
        {
            var sTP_ProductionFinalize2StringParameter = sTP_ProductionFinalize2String != null ?
                new ObjectParameter("STP_ProductionFinalize2String", sTP_ProductionFinalize2String) :
                new ObjectParameter("STP_ProductionFinalize2String", typeof(string));
    
            var precision_ProductionFinalize2StringParameter = precision_ProductionFinalize2String != null ?
                new ObjectParameter("Precision_ProductionFinalize2String", precision_ProductionFinalize2String) :
                new ObjectParameter("Precision_ProductionFinalize2String", typeof(string));
    
            var packingFinalize2StringParameter = packingFinalize2String != null ?
                new ObjectParameter("PackingFinalize2String", packingFinalize2String) :
                new ObjectParameter("PackingFinalize2String", typeof(string));
    
            var loomFinalize2StringParameter = loomFinalize2String != null ?
                new ObjectParameter("LoomFinalize2String", loomFinalize2String) :
                new ObjectParameter("LoomFinalize2String", typeof(string));
    
            var summarySpinningFinalize2StringParameter = summarySpinningFinalize2String != null ?
                new ObjectParameter("SummarySpinningFinalize2String", summarySpinningFinalize2String) :
                new ObjectParameter("SummarySpinningFinalize2String", typeof(string));
    
            var summaryLoomFinalize2StringParameter = summaryLoomFinalize2String != null ?
                new ObjectParameter("SummaryLoomFinalize2String", summaryLoomFinalize2String) :
                new ObjectParameter("SummaryLoomFinalize2String", typeof(string));
    
            var powerHistoryFinalize2StringParameter = powerHistoryFinalize2String != null ?
                new ObjectParameter("PowerHistoryFinalize2String", powerHistoryFinalize2String) :
                new ObjectParameter("PowerHistoryFinalize2String", typeof(string));
    
            var powerHistoryLoomFinalize2StringParameter = powerHistoryLoomFinalize2String != null ?
                new ObjectParameter("PowerHistoryLoomFinalize2String", powerHistoryLoomFinalize2String) :
                new ObjectParameter("PowerHistoryLoomFinalize2String", typeof(string));
    
            var oldInvoiceParameter = oldInvoice != null ?
                new ObjectParameter("OldInvoice", oldInvoice) :
                new ObjectParameter("OldInvoice", typeof(string));
    
            var pdFirstParameter = pdFirst != null ?
                new ObjectParameter("pdFirst", pdFirst) :
                new ObjectParameter("pdFirst", typeof(string));
    
            var pdSecondParameter = pdSecond != null ?
                new ObjectParameter("pdSecond", pdSecond) :
                new ObjectParameter("pdSecond", typeof(string));
    
            var pFirstParameter = pFirst != null ?
                new ObjectParameter("pFirst", pFirst) :
                new ObjectParameter("pFirst", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var unitParameter = unit.HasValue ?
                new ObjectParameter("Unit", unit) :
                new ObjectParameter("Unit", typeof(long));
    
            var dailyFinalize2Parameter = dailyFinalize2 != null ?
                new ObjectParameter("DailyFinalize2", dailyFinalize2) :
                new ObjectParameter("DailyFinalize2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SaveFinalize2", sTP_ProductionFinalize2StringParameter, precision_ProductionFinalize2StringParameter, packingFinalize2StringParameter, loomFinalize2StringParameter, summarySpinningFinalize2StringParameter, summaryLoomFinalize2StringParameter, powerHistoryFinalize2StringParameter, powerHistoryLoomFinalize2StringParameter, oldInvoiceParameter, pdFirstParameter, pdSecondParameter, pFirstParameter, dateParameter, unitParameter, dailyFinalize2Parameter);
        }
    }
}
