//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN_Jute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummarySpinningFinalize2
    {
        public long Id { get; set; }
        public Nullable<long> Unit { get; set; }
        public string Section { get; set; }
        public Nullable<double> A_Hands { get; set; }
        public Nullable<double> B_Hands { get; set; }
        public Nullable<double> C_Hands { get; set; }
        public Nullable<double> Total_ABC_Hands { get; set; }
        public Nullable<System.DateTime> ProductionEntryDate { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
    }
}
